spring:
  datasource:
    url: jdbc:mysql://localhost:3306/annualwork
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
